### ISSUE TITLE
As a User I want to add items to Daily Sales

### ISSUE THREAD

**Issue by kulathilake** [SKYSYS-2018/sithumiTradings#13]
- Selecting Shop Name, Item Name and Quantity
- The whole process is preferred on a single Interface
- Relevant Items need to be reduced from the Inventory

**Comment by RavinduSachintha** [comment]
@Danushka96 is this done?? Otherwise assign someone else without you & me.

**Comment by Danushka96** [comment]
Need someone to implement this task :/ 
See how the buy controllers are implemented and remodel the selling controllers.

**Comment by kulathilake** [comment]
Shall I?

**Comment by kulathilake** [comment]
Does the User have to enter the Selling Price each time he does a sale?

**Comment by Danushka96** [comment]
We auto-fill the selling price which is currently stored in the table. if he wishes to change he can type there.
