### ISSUE TITLE
Observablelist doesn't update the Table View

### ISSUE THREAD

**Issue by kulathilake** [SKYSYS-2018/sithumiTradings#27]
Addition of new items to an invoice does not update the Table view, yet writes to database and the additions are shown when the same invoice is checked by hard coding the invoice into the controller.  I'll move on to the rest of the features as I can't seem to find a solution to this.

controllers.sellController.java

**Comment by Danushka96** [comment]
ok, Push the code. Let's try to solve the problem.

**Comment by kulathilake** [comment]
Pushed to origin->Sales

**Comment by kulathilake** [comment]
Solved! :)
